### ISSUE TITLE
ERROR: stderr: SASL/EXTERNAL authentication started SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth

### ISSUE THREAD

**Issue by qasims** [AAROC/DevOps#241] opened 2015-07-02 11:58 UTC
I am running following and getting an error.
```Shell
ansible-playbook -k -u root --ask-vault-pass /etc/ansible/idp-ld                                                                                                                               ap.yml
SSH password:
SUDO password[defaults to SSH password]:
Vault password:

PLAY [Configure the LDAP machine] *********************************************

GATHERING FACTS ***************************************************************
ok: [idp.se.ampr.org]

TASK: [fmarco76.firewall | Retrieve iptables rules] ***************************
ok: [idp.se.ampr.org]

TASK: [fmarco76.firewall | Count iptables rules] ******************************
ok: [idp.se.ampr.org]

TASK: [fmarco76.firewall | Apply rules for the local network] *****************
skipping: [idp.se.ampr.org] => (item=389)
skipping: [idp.se.ampr.org] => (item=636)

TASK: [fmarco76.firewall | Apply rules for the defined network] ***************
skipping: [idp.se.ampr.org] => (item=389)
skipping: [idp.se.ampr.org] => (item=636)

TASK: [fmarco76.firewall | Apply nat rules] ***********************************
skipping: [idp.se.ampr.org] => (item=389)
skipping: [idp.se.ampr.org] => (item=636)

TASK: [fmarco76.firewall | Save iptable rules] ********************************
skipping: [idp.se.ampr.org]

TASK: [fmarco76.firewall | Save iptable rules] ********************************
skipping: [idp.se.ampr.org]

TASK: [ldap | what are we installing?] ****************************************
ok: [idp.se.ampr.org] => {
    "msg": "['slapd', 'ldap-utils'] will be installed in /etc/ldap"
}

TASK: [ldap | Install the openldap and required Packages for RedHat] **********
skipping: [idp.se.ampr.org]

TASK: [ldap | Install the openldap and required Packages for Debian] **********
ok: [idp.se.ampr.org] => (item=slapd,ldap-utils)

TASK: [ldap | Start ldap server] **********************************************
ok: [idp.se.ampr.org]

TASK: [ldap | Retrieve ldap server configuration] *****************************
ok: [idp.se.ampr.org]

TASK: [ldap | Copy modules file LDIF] *****************************************
skipping: [idp.se.ampr.org]

TASK: [ldap | Add modules (Debian)] *******************************************
skipping: [idp.se.ampr.org]

TASK: [ldap | Add modules (RedHat)] *******************************************
skipping: [idp.se.ampr.org]

TASK: [ldap | Restart ldap server] ********************************************
skipping: [idp.se.ampr.org]

TASK: [ldap | Create db LDIF] *************************************************
ok: [idp.se.ampr.org]

TASK: [ldap | Customise DB] ***************************************************
failed: [idp.se.ampr.org] => {"changed": true, "cmd": ["ldapmodify", "-Y", "EXTERNAL", "-H", "ldapi:///", "-f", "/tmp/db.ldif"], "delta": "0:00:00.024066", "end": "2015-07-02 13:37:02.313845", "rc": 21, "start": "2015-07-02 13:37:02.289779", "warnings": []}
stderr: SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
ldap_modify: Invalid syntax (21)
        additional info: olcRootPW: value #0 invalid per syntax
stdout: modifying entry "olcDatabase={1}hdb,cn=config"

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/qasim/idp-ldap.retry

idp.se.ampr.org            : ok=11   changed=0    unreachable=0    failed=1

```

**Comment by brucellino** [comment] 2015-07-02 12:02
Please check that the remote file `/tmp/db.ldif` has been templated correctly. This is a commonly-reported error and the cause is usually that the root password is either incorrect or not set.

You should have something in `ldap:///tmp/db.ldif` similar to : 

```ldiff
dn: olcDatabase={2}bdb,cn=config
changeType: modify
replace: olcAccess
olcAccess: to attrs=userPassword,shadowLastChange by self write by anonymous auth by dn="cn=admin,dc=local" write by group/groupOfUniqueNames/uniqueMember="cn=Administrator,ou=Group,dc=idp,ou=Services,dc=local" write by * none
olcAccess: to dn.base="" by * read
olcAccess: to * by self write by dn="cn=admin,dc=local" write by group/groupOfUniqueNames/uniqueMember="cn=Administrator,ou=Group,dc=idp,ou=Services,dc=local" write by * read
-
replace: olcSuffix
olcSuffix: dc=local
-
replace: olcRootDN
olcRootDN: cn=admin,dc=local
-
replace: olcRootPW
olcRootPW: <yourpasswordhere>
```

**Comment by qasims** [comment] 2015-07-02 12:15
It is 100% same as you mentioned above. So what is the issue?

**Comment by brucellino** [comment] 2015-07-02 12:20
Ah ! to be honest, I don't know, sorry :disappointed: If it's not a missing password or incorrect one, then I can't help you. I'll assign this to @fmarco76 who has better knowledge of ldap than me. In the meantime, if you could help out by looking on StackExchange or other parts for similar errors and their suggested solutions, that would really help !

**Comment by fmarco76** [comment] 2015-07-03 09:17
The error is about the syntax. Can you post the file you have in `/tmp/db.ldif` file in the LDAP machine?  Do not remove the password but change it after for security reasons.

**Comment by qasims** [comment] 2015-07-03 09:26
```Shell

dn: olcDatabase={1}hdb,cn=config
changeType: modify
replace: olcAccess
olcAccess: to attrs=userPassword,shadowLastChange by self write by anonymous auth by dn="cn=a$
olcAccess: to dn.base="" by * read
olcAccess: to * by self write by dn="cn=admin,dc=local" write by group/groupOfUniqueNames/uni$
-
replace: olcSuffix
olcSuffix: dc=local
-
replace: olcRootDN
olcRootDN: cn=admin,dc=local
-
replace: olcRootPW
olcRootPW:

```

**Comment by fmarco76** [comment] 2015-07-03 09:32
The password is not there.

You miss some variable in your configuration. In more detail the variable root_password is not defined.

**Closed by fmarco76** 2015-07-03 09:32 UTC
Labels: support

**Comment by qasims** [comment] 2015-07-03 09:35
Yes password is not there. Where I can define that variable? in the same file or somewhere else?

**Comment by qasims** [comment] 2015-07-03 16:38
@brucellino 
I found this old issue reported by you. https://github.com/AAROC/DevOps/issues/156 I didn't get where to specify root password?

**Comment by qasims** [comment] 2015-07-04 07:38
Thanks guys for pointing me to right direction. I fixed the password in /etc/ansible/roles/ldap/vars/main.yml and it went well.
