### ISSUE TITLE
Error when executing IdP-LDAP playbook

### ISSUE THREAD

**Issue by WaelSAfifi** [AAROC/DevOps#218] opened 2015-05-12 13:06 UTC
@brucellino @fmarco76 

When trying to execute the IdP-LDAP playbook using this command:

```bash
$ ansible-playbook -i inventory.identity.dev idp-ldap.yml -k -u root -vvvv
```
We got the following error message:

```bash
TASK: [ldap | Apply overlays] *************************************************
<eri_idp_ldap> ESTABLISH CONNECTION FOR USER: root
<eri_idp_ldap> REMOTE_MODULE command ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/overlays.ldif
<eri_idp_ldap> EXEC sshpass -d11 ssh -C -tt -vvv -o ControlMaster=auto -o HostbasedAuthentication=yes -o StrictHostKeyChecking=no -o Port=22 -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o ConnectTimeout=10 eri_idp_ldap /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1431439493.09-133998461364488 && echo $HOME/.ansible/tmp/ansible-tmp-1431439493.09-133998461364488'
<eri_idp_ldap> PUT /tmp/tmpvEqL4X TO /root/.ansible/tmp/ansible-tmp-1431439493.09-133998461364488/command
<eri_idp_ldap> EXEC sshpass -d11 ssh -C -tt -vvv -o ControlMaster=auto -o HostbasedAuthentication=yes -o StrictHostKeyChecking=no -o Port=22 -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o ConnectTimeout=10 eri_idp_ldap /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=fellcevtlwmcwoqhbashmhsmrhbmfwcx] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-fellcevtlwmcwoqhbashmhsmrhbmfwcx; LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1431439493.09-133998461364488/command; rm -rf /root/.ansible/tmp/ansible-tmp-1431439493.09-133998461364488/ >/dev/null 2>&1'"'"''
failed: [eri_idp_ldap] => {"changed": true, "cmd": ["ldapadd", "-Y", "EXTERNAL", "-H", "ldapi:///", "-f", "/tmp/overlays.ldif"], "delta": "0:00:00.008266", "end": "2015-05-12 16:04:53.987781", "rc": 21, "start": "2015-05-12 16:04:53.979515", "warnings": []}
stderr: SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
ldap_add: Invalid syntax (21)
        additional info: objectClass: value #3 invalid per syntax
stdout: adding new entry "olcOverlay=ppolicy,olcDatabase={1}hdb,cn=config"

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/idp-ldap.retry

eri_idp_ldap            : ok=12   changed=1    unreachable=0    failed=1
```

 We also got a similar error when we checked the status of the slapd service as indicated below:

```
May 12 16:04:53 idp.eri slapd[34383]: conn=1000 op=1 ADD dn="olcOverlay=ppolicy,olcDatabase={1}hdb,cn=config"
May 12 16:04:53 idp.eri slapd[34383]: conn=1000 op=1 RESULT tag=105 err=21 text=objectClass: value #3 invalid per syntax
```

How do you think we can solve this problem?

**Comment by brucellino** [comment] 2015-05-12 13:17
Hi @WaelSAfifi , thanks for the report :bow:  Two things : 

As it stands, it's hard to understand what's triggering this error. I can't tell for example which task it's failing on.

Please : 

  1. please increase the verbosity of the playbook ( `-vvv` )
  1. Attach the full output of the playbook (clean passwords or other sensitive information).
 
Thanks !

**Comment by WaelSAfifi** [comment] 2015-05-12 13:37
Sorry, I update the post to be more clear.
The output of the playbook is too long, but it ends with unfinished task as shown below.

----------------------------------------------------------------------------------------------------------------------
TASK: [ldap | Apply overlays] *************************************************
<eri_idp_ldap> ESTABLISH CONNECTION FOR USER: root
<eri_idp_ldap> REMOTE_MODULE command ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/overlays.ldif
<eri_idp_ldap> EXEC sshpass -d11 ssh -C -tt -vvv -o ControlMaster=auto -o HostbasedAuthentication=yes -o StrictHostKeyChecking=no -o Port=22 -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o ConnectTimeout=10 eri_idp_ldap /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1431439493.09-133998461364488 && echo $HOME/.ansible/tmp/ansible-tmp-1431439493.09-133998461364488'
<eri_idp_ldap> PUT /tmp/tmpvEqL4X TO /root/.ansible/tmp/ansible-tmp-1431439493.09-133998461364488/command
<eri_idp_ldap> EXEC sshpass -d11 ssh -C -tt -vvv -o ControlMaster=auto -o HostbasedAuthentication=yes -o StrictHostKeyChecking=no -o Port=22 -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o ConnectTimeout=10 eri_idp_ldap /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=fellcevtlwmcwoqhbashmhsmrhbmfwcx] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-fellcevtlwmcwoqhbashmhsmrhbmfwcx; LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1431439493.09-133998461364488/command; rm -rf /root/.ansible/tmp/ansible-tmp-1431439493.09-133998461364488/ >/dev/null 2>&1'"'"''
failed: [eri_idp_ldap] => {"changed": true, "cmd": ["ldapadd", "-Y", "EXTERNAL", "-H", "ldapi:///", "-f", "/tmp/overlays.ldif"], "delta": "0:00:00.008266", "end": "2015-05-12 16:04:53.987781", "rc": 21, "start": "2015-05-12 16:04:53.979515", "warnings": []}
stderr: SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
ldap_add: Invalid syntax (21)
        additional info: objectClass: value #3 invalid per syntax
stdout: adding new entry "olcOverlay=ppolicy,olcDatabase={1}hdb,cn=config"

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/idp-ldap.retry

eri_idp_ldap            : ok=12   changed=1    unreachable=0    failed=1
-----------------------------------------------------------------------------------------------------
Thanks.

**Comment by brucellino** [comment] 2015-05-12 13:56
ok, this is clearly an LDAP issue. I will assign to @fmarco76. Can you please post us the cleaned contents of /tmp/overlays.ldif on the LDAP host.

It is most likely due to missing variables, so could you also show us the group_vars for your site.

See [https://github.com/AAROC/DevOps/blob/dev/Ansible/group_vars/identity.example](https://github.com/AAROC/DevOps/blob/dev/Ansible/group_vars/identity.example) for an example

**Comment by WaelSAfifi** [comment] 2015-05-12 23:13
The contents of /tmp/overlays.ldif is:
-------------------------------------------------------------------------------------
dn: olcOverlay=ppolicy,olcDatabase={1}hdb,cn=config
objectClass: top
objectClass: olcConfig
objectClass: olcOverlayConfig
objectClass: olcPPolicyConfig
olcOverlay: ppolicy
olcPPolicyDefault: cn=default,ou=policies,dc=local
olcPPolicyHashCleartext: TRUE

dn: olcOverlay=memberof,olcDatabase={1}hdb,cn=config
objectClass: top
objectClass: olcConfig
objectClass: olcOverlayConfig
objectClass: olcMemberOf
olcOverlay: {1}memberof
olcMemberOfMemberAD: uniqueMember
olcMemberOfGroupOC: groupOfUniqueNames
olcMemberOfRefInt: TRUE
olcMemberOfDangling: drop
------------------------------------------------------------------------------------
Regarding the group_vars, I already had defined the LDAP and IdP variables in /Ansible/group_vars/identity-all as follows:
------------------------------------------------------------------------------------
---
# institute metadata
site_name: EG-ERI
host_institute:
  name: ERI Electronic Research Institute
  url: http://www.eri.sci.eg

# LDAP variables
server_country: EG
server_state:
server_location: Cairo
server_organization: ERI
server_organization_unit: HPCloud
organisation:
  name: ERI
  logo: HPCloud
ldap_server: 192.168.195.129
sgw_admin: salma.eri@gmail.com
mail_contact: salma_7975@hotmail.com
# IDP variables. these are specifically related to the IdPOpen Web front end.
idp:
  name: Catch-All Identity Provider
  admin_user: Wael
  admin_email: waelsafifi17@gmail.com
  metadata_url: https://{{ hostvars[groups['shibboleth-idps'][0]]['ansible_fqdn']}}/idp/shibboleth
  mail_server: mail.eri.sci.eg
#  header_logo: Logo.jpg
-------------------------------------------------------------------------------------------------------------------

**Comment by WaelSAfifi** [comment] 2015-05-13 12:19
The contents of /tmp/overlays.ldif is:
-------------------------------------------------------------------------------------
dn: olcOverlay=ppolicy,olcDatabase={1}hdb,cn=config
objectClass: top
objectClass: olcConfig
objectClass: olcOverlayConfig
objectClass: olcPPolicyConfig
olcOverlay: ppolicy
olcPPolicyDefault: cn=default,ou=policies,dc=local
olcPPolicyHashCleartext: TRUE

dn: olcOverlay=memberof,olcDatabase={1}hdb,cn=config
objectClass: top
objectClass: olcConfig
objectClass: olcOverlayConfig
objectClass: olcMemberOf
olcOverlay: {1}memberof
olcMemberOfMemberAD: uniqueMember
olcMemberOfGroupOC: groupOfUniqueNames
olcMemberOfRefInt: TRUE
olcMemberOfDangling: drop
------------------------------------------------------------------------------------
Regarding the group_vars, I already had defined the LDAP and IdP variables in /Ansible/group_vars/identity-all as follows:
------------------------------------------------------------------------------------
---
# institute metadata
site_name: EG-ERI
host_institute:
  name: ERI Electronic Research Institute
  url: http://www.eri.sci.eg

# LDAP variables
server_country: EG
server_state:
server_location: Cairo
server_organization: ERI
server_organization_unit: HPCloud
organisation:
  name: ERI
  logo: HPCloud
ldap_server: 192.168.195.129
sgw_admin: salma.eri@gmail.com
mail_contact: salma_7975@hotmail.com
# IDP variables. these are specifically related to the IdPOpen Web front end.
idp:
  name: Catch-All Identity Provider
  admin_user: Wael
  admin_email: waelsafifi17@gmail.com
  metadata_url: https://{{ hostvars[groups['shibboleth-idps'][0]]['ansible_fqdn']}}/idp/shibboleth
  mail_server: mail.eri.sci.eg
#  header_logo: Logo.jpg
-------------------------------------------------------------------------------------------------------------------

**Comment by brucellino** [comment] 2015-05-13 13:42
Hi @WaelSAfifi - I think this may be due to incompatible directory structure. Can you please help me verify by running 

`ldapadd -Y EXTERNAL -H, ldapi:/// -f /tmp/overlays.ldif`

on the ldap machine , and give us the full output ? 

Thanks

**Comment by WaelSAfifi** [comment] 2015-05-13 13:51
Hi @brucellino .

This is the full output:

SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "olcOverlay=ppolicy,olcDatabase={1}hdb,cn=config"
ldap_add: Invalid syntax (21)
        additional info: objectClass: value #3 invalid per syntax
-----------------------
Thanks.

**Comment by brucellino** [comment] 2015-05-13 14:02
ok, I think the most likely candidate is that your `root_password_clear` variable is not set. It should be in your your `group_vars` *and* the hosts that you are configuring should be in the group defined by your `group_vars` (check your inventory to confirm this).

**Comment by WaelSAfifi** [comment] 2015-05-13 14:48
I set the root_password_clear variable in Ansible/group_vars/identity-all .However, I got the same error when I executed the IdP-LDAP playbook then.
Also the configuring hosts are defined in the same file (i.e., Ansible/group_vars/identity-all) as you could see from its contents in my previous comment. 
In addition, the contents of my inventory is as follows:
_____________________________________________________________________
[ldap-servers]
192.168.195.129

[shibboleth-idps]
192.168.195.129

# We need to include the mapping between science gateways and db servers
[science-gateways]
# We don't support Debian yet
# vm01.ct.infn.it ansible_ssh_port=4422 min_jvm_size=1024m max_jvm_size=1024m db-server=vm02.ct.infn.it
192.168.195.130 min_jvm_size=1024m max_jvm_size=1024m db-server=192.168.195.130 needs_certificate="false"

[db-servers]
192.168.195.130 needs_certificate="false"

[CentOS-servers]
192.168.195.130

[Debian-servers]
192.168.195.129

[identity.dev:children]
ldap-servers
shibboleth-idps
db-servers
science-gateways

[site-test-1:children]
Debian-servers

[site-test-2:children]
CentOS-servers
############################ END #########################

**Comment by brucellino** [comment] 2015-05-13 14:51
ok, I think this is the problem - you don't have a group `identity-all`. you should just move the variables from `group_vars/identity_all` to `group_vars/identity.dev`

First try that. 

however, a better idea (if that works) is to create a new group for your site. The group name in the inventory corresponds to the name of the file in group_vars. You can have something like

```
[eri:children]
ldap-servers
.
.
.
```
and `group_vars/eri` for the variables.

**Comment by sherif-saif** [comment] 2015-05-16 15:13
Hello Bruce

Unfortunately, the same error persists:
====================
failed: [192.168.195.129] => {"changed": true, "cmd": ["ldapadd", "-Y", "EXTERNAL", "-H", "ldapi:///", "-f", "/tmp/overlays.ldif"], "delta": "0:00:00.008202", "end": "2015-05-16 19:04:21.617729", "rc": 21, "start": "2015-05-16 19:04:21.609527", "warnings": []}
stderr: SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
ldap_add: Invalid syntax (21)
        additional info: objectClass: value #3 invalid per syntax
stdout: adding new entry "olcOverlay=ppolicy,olcDatabase={1}hdb,cn=config"

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/idp-ldap.retry
192.168.195.129            : ok=12   changed=1    unreachable=0    failed=1
==========================================================
The contents of the file identity.dev file were modified as shown below:

[root@idp Ansible]# pwd
/home/ansible/DevOps/Ansible
[root@idp Ansible]# cat group_vars/identity.dev
---
# institute metadata
site_name: EG-ERI
host_institute:
  name: ERI Electronic Research Institute
  url: http://www.eri.sci.eg

# LDAP variables
server_country: EG
server_state:
server_location: Cairo
server_organization: ERI
server_organization_unit: HPCloud
organisation:
  name: ERI
  logo: HPCloud
ldap_server: 192.168.195.129
sgw_admin: salma.eri@gmail.com
mail_contact: salma_7975@hotmail.com
root_password_clear: *********

# IDP variables. these are specifically related to the IdPOpen Web front end.
idp:
  name: Catch-All Identity Provider
  admin_user: Wael
  admin_email: waelsafifi17@gmail.com
  metadata_url: https://{{ hostvars[groups['shibboleth-idps'][0]]['ansible_fqdn']}}/idp/shibboleth
  mail_server: mail.eri.sci.eg
#  header_logo: Logo.jpg

**Comment by brucellino** [comment] 2015-05-28 13:34
I've asked this question on ServerFault : http://serverfault.com/questions/691750/what-does-the-ldapadd-error-additional-info-objectclass-value-3-invalid-per 

The first answer seems to be that this is simply a syntax error, however, I'm not sure what's generating it.

**Comment by WaelSAfifi** [comment] 2015-06-23 09:55
Dear Bruce,

Is there any updates about this issue?

I changed the idp machine from being on the same Ansible machine (running with CentOS-7) to a separate machine running with CentOS-6 as tested and preferred by your side, but we got the same error when we execute the IdP-LDAP playbook command.

**Comment by brucellino** [comment] 2015-07-01 05:03
Hi @WaelSAfifi sorry for the delay. I have not been able to reproduce this error which leads me to believe that there is some difference between the openldap versions on your machine and ours, which has changed the slapd configuration.

Can you show me what's in `/etc/openldap` and `/etc/openldap/slapd.conf`. You should have something like

```bash
[root@ldap openldap]# ls
certs  ldap.conf  schema  slapd.d
```
and 
```bash
[root@ldap openldap]# ls slapd.d/
cn=config  cn=config.ldif
[root@ldap openldap]# ls slapd.d/cn\=config
cn=module{0}.ldif  cn=schema.ldif              olcDatabase={-1}frontend.ldif  olcDatabase={2}bdb
cn=schema          olcDatabase={0}config.ldif  olcDatabase={1}monitor.ldif    olcDatabase={2}bdb.ldif
```

can you confirm please ?

**Comment by brucellino** [comment] 2016-02-03 17:42
Hi 

Any update on this issue ?

**Closed** 2016-08-02 12:05 UTC
Labels: Ansible syntax, bug, support
