### ISSUE TITLE
could not create domain, liferay

### ISSUE THREAD

**Issue by GhadaFathy** [AAROC/DevOps#216] opened 2015-05-05 11:00 UTC
when we try to install science gateway using this command ansible-playbook -i inventories/inventory.mucsat.sci.eg liferay-csgf.yml 
 we got this error 
failed: [vm01.mucsat.sci.eg] => {"changed": true, "cmd": "./asadmin --interactive false --passwordfile /home/liferayadmin/passwordfile --user liferayadmin create-domain liferay", "delta": "0:00:05.818495", "end": "2015-05-05 06:18:53.877867", "rc": 1, "start": "2015-05-05 06:18:48.059372", "warnings": []}
stderr: CLI130 Could not create domain, liferay
stdout: Default port 4848 for Admin is in use. Using 34562
Default port 8080 for HTTP Instance is in use. Using 36108
Default port 7676 for JMS is in use. Using 41391
Default port 3700 for IIOP is in use. Using 55501
Default port 8181 for HTTP_SSL is in use. Using 45413
Default port 3820 for IIOP_SSL is in use. Using 44571
Default port 3920 for IIOP_MUTUALAUTH is in use. Using 53187
Default port 8686 for JMX_ADMIN is in use. Using 35844
Default port 6666 for OSGI_SHELL is in use. Using 40810
Default port 9009 for JAVA_DEBUGGER is in use. Using 39552
Port 34,562 is in use
Command create-domain failed.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/liferay-csgf.retry

vm01.mucsat.sci.eg         : ok=69   changed=11   unreachable=0    failed=1
 
we used the domin.yml as mentioned in https://github.com/AAROC/DevOps/issues/178
but still not working

**Comment by fmarco76** [comment] 2015-05-06 16:23
It seems there is an instance of liferay running in the serve but with a problem and ansible cannot identify the running service. Did you run the command in a new machine or there was liferay already?

**Comment by brucellino** [comment] 2015-05-12 13:59
@GhadaFathy  - did you manage to reproduce the problem, or have you solved it ? :pray: Bruce

**Comment by MohamedFattah** [comment] 2015-05-13 13:26
Hi,
we have started the installation in a new machine to be sure there's no previous liferay installation
and we ran in the same error

TASK: [liferay-csgf | create liferay domain] **********************************
<vm01.mucsat.sci.eg> ESTABLISH CONNECTION FOR USER: ansible on PORT 22 TO vm01.mucsat.sci.eg
<vm01.mucsat.sci.eg> REMOTE_MODULE command ./asadmin --interactive false --passwordfile /home/liferayadmin/passwordfile --user liferayadmin create-domain liferay chdir=/opt/glassfish/glassfish3/bin/ #USE_SHELL
<vm01.mucsat.sci.eg> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-tmp-1431522392.31-138123883022249 && chmod a+rx /tmp/ansible-tmp-1431522392.31-138123883022249 && echo /tmp/ansible-tmp-1431522392.31-138123883022249'
<vm01.mucsat.sci.eg> PUT /tmp/tmptPGl_4 TO /tmp/ansible-tmp-1431522392.31-138123883022249/command
<vm01.mucsat.sci.eg> EXEC /bin/sh -c 'chmod a+r /tmp/ansible-tmp-1431522392.31-138123883022249/command'
<vm01.mucsat.sci.eg> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=wipntzogzkitrhlrcqciuxzgdpubmlwi] password: " -u liferayadmin /bin/sh -c '"'"'echo BECOME-SUCCESS-wipntzogzkitrhlrcqciuxzgdpubmlwi; LANG=C LC_CTYPE=C /usr/bin/python /tmp/ansible-tmp-1431522392.31-138123883022249/command'"'"''
<vm01.mucsat.sci.eg> EXEC /bin/sh -c 'rm -rf /tmp/ansible-tmp-1431522392.31-138123883022249/ >/dev/null 2>&1'
failed: [vm01.mucsat.sci.eg] => {"changed": true, "cmd": "./asadmin --interactive false --passwordfile /home/liferayadmin/passwordfile --user liferayadmin create-domain liferay", "delta": "0:00:06.512923", "end": "2015-05-13 09:06:40.737680", "rc": 1, "start": "2015-05-13 09:06:34.224757", "warnings": []}
stderr: CLI130 Could not create domain, liferay
stdout: Default port 4848 for Admin is in use. Using 55073
Default port 8080 for HTTP Instance is in use. Using 46600
Default port 7676 for JMS is in use. Using 51934
Default port 3700 for IIOP is in use. Using 41565
Default port 8181 for HTTP_SSL is in use. Using 38927
Default port 3820 for IIOP_SSL is in use. Using 40049
Default port 3920 for IIOP_MUTUALAUTH is in use. Using 45559
Default port 8686 for JMX_ADMIN is in use. Using 40266
Default port 6666 for OSGI_SHELL is in use. Using 37442
Default port 9009 for JAVA_DEBUGGER is in use. Using 34397
Port 55,073 is in use
Command create-domain failed.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/liferay-csgf.retry

vm01.mucsat.sci.eg         : ok=73   changed=50   unreachable=0    failed=1


======

Then we tried the following to check the default port 4848 for Admin
[root@vm01 ~]# netstat -tulpn | grep 4848
 and the port wasn't in use

Any advice :)

**Comment by brucellino** [comment] 2015-05-14 09:14
Hello @GhadaFathy, you are right that the error is diagnosed by the line : 
```
stdout: Default port 4848 for Admin is in use. Using 55073
```
however, this is usually a symptom of a preexisting java instance runing. Can you chekc if there are any java processes - do 
```
ps aux | grep java
```

**Comment by magfathy** [comment] 2015-05-14 10:54
Hi Bruce,

we do the command "ps aux | grep java"  and there was java
     root      8023  0.0  0.0 103240   880 pts/0    S+   06:50   0:00 grep java
then we removed it and run the plabook again
    ansible-playbook -i inventories/inventory.mucsat.sci.eg liferay-csgf.yml -v -vvvvv
and the same error happened again and we found a new installation of java.

**Comment by brucellino** [comment] 2015-05-15 12:01
I'm going to put this on hold until next week, if you don't mind, so we can take a closer look at it.

**Comment by MohamedFattah** [comment] 2015-05-18 10:36
Hi Bruce,

What do you think about what can we do in Lifery error: "could not create domain, liferay #216" Error.

**Comment by brucellino** [comment] 2015-05-28 16:30
To summarise what we said today during the meeting, this issue is generated by a glassfish server already running. 

Could you please do a 

```bash
asadmin list-domains
```

and let us know what it shows ?

**Comment by MohamedFattah** [comment] 2015-05-31 08:54
It showed the following:

[root@ansible-controller Ansible]# asadmin list-domains
Traceback (most recent call last):
  File "/usr/bin/asadmin", line 260, in <module>
    autoscale = boto.connect_autoscale()
  File "/usr/lib/python2.6/site-packages/boto/__init__.py", line 197, in connect_autoscale
    **kwargs)
  File "/usr/lib/python2.6/site-packages/boto/ec2/autoscale/__init__.py", line 124, in __init__
    validate_certs=validate_certs)
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 998, in __init__
    validate_certs=validate_certs)
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 557, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/lib/python2.6/site-packages/boto/auth.py", line 728, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials

**Comment by brucellino** [comment] 2015-06-01 11:38
I've never seen this before - I think there are some things a bit off here.

  1. It seems like you're running `./asadmin` on the controller machine. If this is the _same_ as the science-gateway, that's ok - please confirm.
  1. This looks like you're getting a python error, but `asadmin` is a script to control the glassfish server. Are you sure you're running the right command. It should be `/path/to/glassfish/bin/asadmin`

check these two things please.
Bruce

**Comment by MohamedFattah** [comment] 2015-06-01 11:45
We have got the same error when we executed on this path:

/path/to/glassfish/bin/asadmin

**Comment by brucellino** [comment] 2015-06-01 12:26
Hi @MohamedFattah ! Sorry, I should have been a bit clearer - 

`/path/to/glassfish/bin/asadmin` is a placeholder for the actual `asadmin` path. Since you can specify where you want to install glassfish, I used a generic path (`/path/to/glassfish`). 

If you used the defaults this path should be : 

`/opt/glassfish/glassfish3/bin/asadmin`

**Comment by MohamedFattah** [comment] 2015-06-01 12:43
yes, we used
/opt/glassfish/glassfish3/bin/asadmin

**Comment by MohamedFattah** [comment] 2015-06-02 09:47
"New status"

After some trying, the previous error has been solved, but the following error has been appeared:
//-----
TASK: [liferay-csgf | Start the Liferay Domain] *******************************

failed: [vm01.mucsat.sci.eg] => {"ansible_job_id": "392420146105.16093", "changed": true, "cmd": "./asadmin --interactive false --passwordfile /home/liferayadmin/passwordfile --user liferayadmin start-domain liferay", "delta": "0:00:02.055706", "end": "2015-06-02 05:30:00.656483", "finished": 1, "rc": 1, "start": "2015-06-02 05:29:58.600777", "warnings": []}
stdout: There is a process already using the admin port 4848 -- it probably is another instance of a GlassFish server.
Command start-domain failed.
<job 392420146105.16093> FAILED on vm01.mucsat.sci.eg

FATAL: all hosts have already failed -- aborting

**Comment by brucellino** [comment] 2015-06-03 07:20
Yes, this is a known issue - we haven't yet implemented the clean shutdown and check of the glassfish server. Just kill the process by hand (`ps aux | grep java`) and re-run starting at the "Start the Liferay Domain" task. In the meantime, I'm going to close this ticket. 

# Solution
There was a glassfish instance running. It was killed by hand and the playbook was re-run.

**Closed by brucellino** 2015-06-03 07:20 UTC
Labels: input needed., on-hold
