### ISSUE TITLE
Problem mounting CVMFS on worker nodes

### ISSUE THREAD

**Issue by smasoka** [AAROC/DevOps#260] opened 2015-08-31 14:50 UTC
So i ran cvmfs playbook on my virtual machine and everything was installed and configured properly, But when I did the same on my worker nodes for ZA_CHPC, repo is not mounting. 
Error: 
`root@gnode-2-1:~ $ cvmfs_config probe`
`Probing /cvmfs/apprepo.sagrid.ac.za... Failed!`
and 
`root@gnode-2-1:~ $ mount -t cvmfs devrepo.sagrid.ac.za /mnt/test`
`CernVM-FS: running with credentials 497:496`
`CernVM-FS: loading Fuse module... Failed to initialize root file catalog (16 - file catalog failure)`

**Comment by brucellino** [comment] 2015-09-01 10:28
Try run the cvmfs.ynl play book on the machines. Or check that the config is the same.

**Comment by smasoka** [comment] 2015-09-01 12:19
Yes, I ran the cvmfs.yml playbook on the worker nodes themselves. 
The config looks the same plus the playbook hasn't been changed right?

**Comment by brucellino** [comment] 2015-09-01 13:12
there are no changes that I still need to commit, but check that you're using the dev branch.

FYI it's working on my laptop and meraka's dev site. Here's the config : 

```bash

cat /etc/cvmfs/config.d/apprepo.sagrid.ac.za.conf 
CVMFS_SERVER_URL=http://apprepo.sagrid.ac.za/cvmfs/apprepo.sagrid.ac.za
CVMFS_HTTP_PROXY=DIRECT
CVMFS_PUBLIC_KEY=/etc/cvmfs/keys/apprepo.sagrid.ac.za.pub

```

and 

```
cat /etc/cvmfs/config.d/devrepo.sagrid.ac.za.conf
CVMFS_SERVER_URL=http://apprepo.sagrid.ac.za/cvmfs/devrepo.sagrid.ac.za
CVMFS_HTTP_PROXY=DIRECT
CVMFS_PUBLIC_KEY=/etc/cvmfs/keys/devrepo.sagrid.ac.za.pub

```

check your config and the proxy.

**Comment by smasoka** [comment] 2015-09-01 15:08
`cat /etc/cvmfs/default.local`
`CVMFS_REPOSITORIES=apprepo.sagrid.ac.za`
`CVMFS_SERVER_URL=http://apprepo.sagrid.ac.za`
`CVMFS_HTTP_PROXY=DIRECT`

and 

` cat /etc/cvmfs/config.d/apprepo.sagrid.ac.za.conf`
`CVMFS_SERVER_URL=http://apprepo.sagrid.ac.za/cvmfs/apprepo.sagrid.ac.za`
`CVMFS_PUBLIC_KEY=/etc/cvmfs/keys/apprepo.sagrid.ac.za.pub`

`cat /etc/cvmfs/config.d/devrepo.sagrid.ac.za.conf`
`CVMFS_SERVER_URL=http://apprepo.sagrid.ac.za/cvmfs/devrepo.sagrid.ac.za`
`CVMFS_PUBLIC_KEY=/etc/cvmfs/keys/devrepo.sagrid.ac.za.pub`

packages:
`rpm -qa|grep cvmfs`
`cvmfs-auto-setup-1.5-1.noarch`
`cvmfs-2.1.20-1.el6.x86_64`
`cvmfs-config-default-1.2-2.noarch`
`cvmfs-release-2-4.el5.noarch`
 and I got the keys installed. 

The very same config is working on my virtual machine. 
I guess its network related on SAGrid nodes, because Alice nodes cvmfs is working fine :(

**Comment by brucellino** [comment] 2016-02-03 17:38
I can't reproduce this - can you comment ? Else I'm going to close this and you can open a new ticket if it re-occurs.

**Comment by brucellino** [comment] 2016-05-11 14:15
This has been fixed by @bazinski  at the site.

**Closed** 2016-05-11 14:16 UTC
Labels: tested
