### ISSUE TITLE
 Error in  liferay-csgf.yml

### ISSUE THREAD

**Issue by Abdelrahman1985** [AAROC/DevOps#201] opened 2015-03-19 12:46 UTC
@brucellino 
ear All,
after i run the playbook  liferay-csgf.yml -- i got the following error : 

TASK: [liferay-csgf | create liferay domain] **********************************
failed: [sgw.asrenorg.net] => {"changed": true, "cmd": "./asadmin --interactive false --passwordfile /home/liferayadmin/passwordfile --user liferayadmin create-domain liferay", "delta": "0:00:00.766069", "end": "2015-03-19 14:39:01.345580", "rc": 1, "start": "2015-03-19 14:39:00.579511", "warnings": []}
stderr: CLI130 Could not create domain, liferay
stdout: Default port 4848 for Admin is in use. Using 38989
Default port 8080 for HTTP Instance is in use. Using 58271
Default port 7676 for JMS is in use. Using 56817
Default port 3700 for IIOP is in use. Using 40614
Default port 8181 for HTTP_SSL is in use. Using 39105
Default port 3820 for IIOP_SSL is in use. Using 33044
Default port 3920 for IIOP_MUTUALAUTH is in use. Using 41649
Default port 8686 for JMX_ADMIN is in use. Using 33284
Default port 6666 for OSGI_SHELL is in use. Using 38091
Default port 9009 for JAVA_DEBUGGER is in use. Using 43192
Port 38,989 is in use
Command create-domain failed.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/liferay-csgf.retry

sgw.asrenorg.net           : ok=69   changed=12   unreachable=0    failed=1

**Comment by Abdelrahman1985** [comment] 2015-03-22 06:05
hi all,
any solution for this problem ?

**Comment by Abdelrahman1985** [comment] 2015-03-23 07:12
we have re-installed the file “iferay-csgf.yml” and we have got the following result
https://github.com/AAROC/DevOps/issues/203

**Comment by brucellino** [comment] 2015-03-24 11:02
Closing this as a dupliate of #203.
The issue is that the sgw and idp are being interpreted as the same host. Although they are specified differently in the inventory (by name), something else is mapping the names of these two machines to the same machine (idp).

**Closed by brucellino** 2015-03-24 11:02 UTC
Labels: bug, not reproducible

**Comment by MohamedFattah** [comment] 2015-05-25 11:25
Hi Abdelrahman-Hasan,

How you re-installed the file “iferay-csgf.yml” ???
